// === シナリオデータ ===
// シナリオβ版v2を忠実に実装
// 各行: { type, speaker, text, bg, bgOverlay, showHolly, hideHolly, bgm, se, label, choices, monologue }

const SCENARIO = [

// =============== PROLOGUE: はじめの青 ===============

// Scene 01: 水戸、初日
{ type:'label', label:'prologue_01' },
{ type:'bg', bg:'residential', bgOverlay:'morning' },
{ type:'bgm', bgm:'warm' },
{ type:'se', se:'scene_change' },
{ type:'scene', text:'PROLOGUE　はじめの青' },
{ type:'label_display', text:'Scene 01　水戸、初日' },
{ type:'text', monologue:true, text:'3月。転勤の辞令から2週間で、わたしは水戸市に引っ越してきた。' },
{ type:'text', monologue:true, text:'朝から荷ほどきをしていたが、段ボールに埋もれた部屋から逃げたくて外に出た。' },
{ type:'text', monologue:true, text:'新しい街は、思ったより静かで、思ったより広くて、\nそして——' },
{ type:'text', monologue:true, text:'（遠くに、コンクリート造のスタジアムらしき建物が見える。バックスタンドに大きく「MITO」の文字。）' },
{ type:'text', monologue:true, text:'……でかい。' },
{ type:'text', monologue:true, text:'あの「MITO」って書いてある建物、スタジアムかな。' },
{ type:'text', monologue:true, text:'地図も見ないまま、なんとなく近づいてみた。\nそこで。' },

// Scene 02: 出会い
{ type:'label', label:'prologue_02' },
{ type:'bg', bg:'stadium_facade', bgOverlay:'morning' },
{ type:'bgm', bgm:'silence' },
{ type:'label_display', text:'Scene 02　出会い' },
{ type:'text', monologue:true, text:'（スタジアムのゲート付近。何かがうずくまっている。青くて、大きくて、丸い何かが。）' },
{ type:'text', monologue:true, text:'……？' },
{ type:'text', monologue:true, text:'動いてる。生きてる。なんだこれ。' },
{ type:'text', speaker:'さくら', text:'あの……大丈夫ですか？' },
{ type:'se', se:'heartbeat' },
{ type:'text', monologue:true, text:'（青いそれがゆっくりと振り返る。龍っぽい顔をしている。目がぱっちりしている。）', showHolly:true },
{ type:'text', speaker:'ホーリーくん', text:'あ。ひと。' },
{ type:'text', speaker:'さくら', text:'ひと、って……あなたも……まあ……' },
{ type:'text', speaker:'ホーリーくん', text:'迷子なんだよね、オレ。' },
{ type:'text', speaker:'さくら', text:'え。' },
{ type:'text', speaker:'ホーリーくん', text:'スタジアムのどこから入るんだっけって思ってたら、出口から出てきちゃって。' },
{ type:'text', monologue:true, text:'スタジアムの出口から出てきたのに迷子……？\nまあ、確かに迷子か……？' },
{ type:'text', speaker:'さくら', text:'えっと、あなた……ホーリーくん、だよね？　見たことある気がする……' },
{ type:'text', speaker:'ホーリーくん', text:'そうだよ。水戸ホーリーホックのホーリーくん。会えてよかった、きみ。' },
{ type:'text', speaker:'さくら', text:'え、なんで「よかった」なの？　今はじめて会ったのに。' },
{ type:'text', speaker:'ホーリーくん', text:'転勤でしょ、さっき越してきた。水戸にいない人には会えないから、会えてよかったってこと。' },
{ type:'text', speaker:'さくら', text:'なんでわかるの……？' },
{ type:'text', speaker:'ホーリーくん', text:'オレ、水戸のこと全部知ってるから。' },
{ type:'text', monologue:true, text:'こわっ。こわ……でも、なんか、嘘をついてる感じがしない。' },
{ type:'text', speaker:'ホーリーくん', text:'今日、試合があるよ。夕方から。スタジアム、案内しようか。' },
{ type:'text', speaker:'さくら', text:'いや、別に……' },
{ type:'text', speaker:'ホーリーくん', text:'行こ。' },
{ type:'text', monologue:true, text:'（問答無用で歩き出す。ゆっくりと。非常にゆっくりと。）' },
{ type:'text', speaker:'さくら', text:'……あ、うん。' },

// Scene 03: スタジアムへ
{ type:'label', label:'prologue_03' },
{ type:'bg', bg:'stadium', bgOverlay:'morning' },
{ type:'bgm', bgm:'bright' },
{ type:'label_display', text:'Scene 03　スタジアムへ' },
{ type:'text', monologue:true, text:'（メインゲート前の広場。キッチンカーが並び始めているが、まだお客はほとんどいない。スタッフやボランティアが準備をしている。）' },
{ type:'text', monologue:true, text:'スタジアムの周りを歩きながら、開場前の雰囲気を見ていた。' },
{ type:'text', monologue:true, text:'食べ物の屋台が並び始めていた。梅の絵が描かれたのぼりが揺れている。' },
{ type:'text', speaker:'さくら', text:'広いね。……収容何人なの？' },
{ type:'text', speaker:'ホーリーくん', text:'1万2千人。満員になると、すごいよ。' },
{ type:'text', speaker:'さくら', text:'満員になるの？' },
{ type:'text', speaker:'ホーリーくん', text:'なるよ。なったことあるよ。' },
{ type:'text', speaker:'さくら', text:'水戸ホーリーホック……J何部なの？' },
{ type:'text', speaker:'ホーリーくん', text:'J2。今シーズン、J1を目指してる。' },
{ type:'text', speaker:'さくら', text:'え、すごいじゃん！' },
{ type:'text', speaker:'ホーリーくん', text:'26年かかったけどね。' },
{ type:'text', speaker:'さくら', text:'……26年。' },
{ type:'text', monologue:true, text:'26年。\nわたしとほぼ同い年じゃないか。' },
{ type:'se', se:'wind' },
{ type:'text', monologue:true, text:'（スタグルのキッチンカーから梅酒の甘酸っぱい香りが漂い始める。）' },
{ type:'text', speaker:'さくら', text:'あのぼりに描いてある、梅のやつ……梅酒？' },
{ type:'text', speaker:'ホーリーくん', text:'百年梅酒。水戸名物。アウェーサポーターにも人気なんだよ。' },
{ type:'text', speaker:'さくら', text:'試合観るのに梅酒……いいね、それ。' },
{ type:'text', speaker:'ホーリーくん', text:'今日、試合観てく？　夕方から。' },
{ type:'text', speaker:'さくら', text:'え、今日？　荷ほどきが……' },
{ type:'text', speaker:'ホーリーくん', text:'段ボールは逃げないから。' },
{ type:'text', speaker:'さくら', text:'……確かに。' },

// 選択肢① フレーバー選択
{ type:'choice', choices:[
  { text:'せっかくだし、見てみる', next:'choice1a', empathy:0 },
  { text:'荷ほどき終わったら来るよ', next:'choice1b', empathy:0 },
]},
{ type:'label', label:'choice1a' },
{ type:'text', speaker:'ホーリーくん', text:'うん。来て正解だよ、絶対。' },
{ type:'jump', to:'scene04' },
{ type:'label', label:'choice1b' },
{ type:'text', speaker:'ホーリーくん', text:'来るってわかってるから、待ってるよ。' },

// Scene 04: 初観戦
{ type:'label', label:'scene04' },
{ type:'bg', bg:'stadium', bgOverlay:'evening' },
{ type:'bgm', bgm:'warm' },
{ type:'se', se:'cheer' },
{ type:'label_display', text:'Scene 04　初観戦' },
{ type:'text', monologue:true, text:'スタジアムに人が増えていた。青いユニフォームが、あちこちで揺れている。' },
{ type:'text', monologue:true, text:'知らなかった。水戸にこんな場所があるなんて。' },
{ type:'text', speaker:'ホーリーくん', text:'ほら、あそこがバックスタンドの一角。サポーターが集まってる。' },
{ type:'text', speaker:'さくら', text:'ずっと歌ってる……' },
{ type:'text', speaker:'ホーリーくん', text:'ずっと歌ってるよ。負けてても、歌ってる。' },
{ type:'text', speaker:'さくら', text:'負けてても？' },
{ type:'text', speaker:'ホーリーくん', text:'うん。それが好きなんだよね、オレ。' },
{ type:'se', se:'cheer' },
{ type:'text', monologue:true, text:'（試合開始。歓声。スタジアムが揺れるような感覚。）' },
{ type:'text', monologue:true, text:'点が入った瞬間、隣のおじさんが飛び上がって、前の子どもが泣いて、後ろの女性が叫んだ。' },
{ type:'text', monologue:true, text:'わたしもなぜか、立ち上がっていた。' },
{ type:'text', monologue:true, text:'なんだろう、これ。' },
{ type:'text', monologue:true, text:'サッカー、ちゃんと見たことなかったのに。\nなんか……すごく、いい。' },
{ type:'text', speaker:'ホーリーくん', text:'楽しい？' },
{ type:'text', speaker:'さくら', text:'……うん。なんか、楽しい。なんでだろ。' },
{ type:'text', speaker:'ホーリーくん', text:'「なんでだろ」でいいんだよ。' },
{ type:'text', monologue:true, text:'（試合終了のホイッスル。結果は引き分けだった。）' },
{ type:'text', monologue:true, text:'（それでも、サポーターは歌い続けていた。）' },
{ type:'text', monologue:true, text:'その夜、段ボールを開けながら、なんとなくスマートフォンで「水戸ホーリーホック」と検索した。' },
{ type:'text', monologue:true, text:'1994年創設。J2参入から26年。今シーズン、ついに首位争いをしている。' },
{ type:'text', monologue:true, text:'「J2の門番」という、少し寂しい呼び名。' },
{ type:'text', monologue:true, text:'そして——26年間、ずっとここにいたマスコット。' },
{ type:'text', monologue:true, text:'……ホーリーくん、26年いるって言ってたな。\n全部、見てきたんだ。' },
{ type:'text', speaker:'さくら', monologue:true, text:'（独り言）今日のこと、聞いてみたいな。' },

// Scene 05: 再会
{ type:'label', label:'prologue_05' },
{ type:'bg', bg:'atsumare', bgOverlay:'afternoon' },
{ type:'bgm', bgm:'bright' },
{ type:'label_display', text:'Scene 05　再会' },
{ type:'text', monologue:true, text:'翌週。なんとなく、もう一度ホーリーくんに会いたくなった。' },
{ type:'text', monologue:true, text:'Ksスタに行ってみたが、試合がない日の競技場は静かで、ホーリーくんの姿はなかった。' },
{ type:'text', monologue:true, text:'スマートフォンで調べると、「アツマーレ」という言葉が出てきた。クラブハウス。城里町。' },
{ type:'text', monologue:true, text:'なんとなく、行ってみた。\n水戸から少し北へ。山に近い、緑の多い場所。町民センターの建物が見えてきた。' },
{ type:'se', se:'heartbeat' },
{ type:'text', speaker:'ホーリーくん', text:'来た。', showHolly:true },
{ type:'text', speaker:'さくら', text:'なんでいるの、ここに！？ってか、ここどこ！？' },
{ type:'text', speaker:'ホーリーくん', text:'アツマーレ。クラブハウス。' },
{ type:'text', speaker:'さくら', text:'……さっきKsスタ行ったのに、いなかった。' },
{ type:'text', speaker:'ホーリーくん', text:'試合がない日はKsスタにはいないよ。ここが本拠地。' },
{ type:'text', speaker:'さくら', text:'……そういうことか。' },
{ type:'text', speaker:'ホーリーくん', text:'また話したいでしょ。ここのこと。' },
{ type:'text', speaker:'さくら', text:'……まあ、ちょっと。26年ってすごいなって思って。' },
{ type:'text', monologue:true, text:'（グラウンドの方から、選手が練習を終えて戻ってくる声が聞こえる。）' },
{ type:'text', speaker:'ホーリーくん', text:'じゃあ聞かせてあげる。どこから行く？' },
{ type:'text', speaker:'さくら', text:'どこから？' },
{ type:'text', speaker:'ホーリーくん', text:'最初から。1994年から。' },
{ type:'text', speaker:'さくら', text:'……ちなみに今、何時間くらいかかる話なの？' },
{ type:'text', speaker:'ホーリーくん', text:'全部話したら26年分だよ。' },
{ type:'text', speaker:'さくら', text:'じゃあ少しずつにしよう。' },
{ type:'text', speaker:'ホーリーくん', text:'うん。一緒に歩こう。ゆっくり。' },
{ type:'text', monologue:true, text:'ゆっくり、か。\nまあ、急いで理解できるような話でもないか。' },

// =============== 第1章: 始まりの葵 ===============
{ type:'label', label:'chapter1' },
{ type:'se', se:'scene_change' },
{ type:'scene', text:'第1章　始まりの葵\n1994〜1996年　草創期' },

// Scene 1-1: 偕楽園 梅まつり
{ type:'bg', bg:'plum', bgOverlay:'afternoon' },
{ type:'bgm', bgm:'warm' },
{ type:'label_display', text:'Scene 1-1　偕楽園　梅まつり' },
{ type:'text', monologue:true, text:'ホーリーくんが「梅まつりに行こう」と言い出したのは、2月の終わりのことだった。' },
{ type:'text', monologue:true, text:'偕楽園。日本三名園のひとつ。100種3000本の梅が咲き誇る。' },
{ type:'text', monologue:true, text:'水戸に来てよかった、と思える場所が、こんなに早く見つかるとは思っていなかった。' },
{ type:'text', monologue:true, text:'（梅の花が一面に広がる景色。ホーリーくんがのそのそ歩いている（ゆっくり）。）', showHolly:true },
{ type:'text', speaker:'さくら', text:'きれいだね。こんなにいっぱいあるんだ。' },
{ type:'text', speaker:'ホーリーくん', text:'水戸の誇りだよ。梅も、葵も。' },
{ type:'text', speaker:'さくら', text:'葵？' },
{ type:'text', speaker:'ホーリーくん', text:'徳川御三家の水戸藩。家紋が葵。ホーリーホック——英語でタチアオイ。葵の花のことだよ。' },
{ type:'text', speaker:'さくら', text:'あ、そういうことか。名前の由来って、そこから来てるの？' },
{ type:'text', speaker:'ホーリーくん', text:'水戸の歴史と、クラブが全部つながってる。' },
{ type:'text', monologue:true, text:'（梅まんじゅうを手にしたさくら。）' },
{ type:'text', speaker:'さくら', text:'梅まんじゅう、おいしい……ホーリーくんも食べる？' },
{ type:'text', speaker:'ホーリーくん', text:'食べる。' },
{ type:'text', speaker:'さくら', text:'……どうやって食べるの？' },
{ type:'text', speaker:'ホーリーくん', text:'（ドヤ顔で）うまく食べるよ。' },
{ type:'text', speaker:'さくら', text:'謎すぎる。' },
{ type:'text', monologue:true, text:'ツッコんだら負けな気がする。ここはスルーしよう。' },

// Scene 1-2: 1994年の話
{ type:'label_display', text:'Scene 1-2　1994年の話' },
{ type:'text', speaker:'さくら', text:'じゃあ聞かせて。1994年って、何があったの？' },
{ type:'text', speaker:'ホーリーくん', text:'クラブができた年だよ。FC水戸ってチームが。' },
{ type:'text', speaker:'さくら', text:'水戸ホーリーホックじゃなくて？' },
{ type:'text', speaker:'ホーリーくん', text:'そのあとね。最初はFC水戸。石山さんっていう人が作ったんだ。' },
{ type:'text', speaker:'さくら', text:'どんな人？' },
{ type:'text', speaker:'ホーリーくん', text:'水戸に、Jリーグのチームを作りたい、って思った人。それだけで動いた人。' },
{ type:'text', speaker:'さくら', text:'それだけで？' },
{ type:'text', speaker:'ホーリーくん', text:'うん。県リーグの4部から始めたんだ。一番下から。' },
{ type:'text', monologue:true, text:'4部……。一番下から、J2まで上がったってこと？' },
{ type:'text', speaker:'さくら', text:'4部って、普通にその辺の草サッカーみたいな感じ？' },
{ type:'text', speaker:'ホーリーくん', text:'まあ、そんな感じ。でも全勝したよ、最初の年。13戦全勝・無失点。' },
{ type:'text', speaker:'さくら', text:'え、強かったじゃん！' },
{ type:'text', speaker:'ホーリーくん', text:'強かったというより……信じてたんだと思う。ここから始められる、って。' },
{ type:'text', monologue:true, text:'（ホーリーくんが梅の花を見上げる。）' },
{ type:'text', speaker:'ホーリーくん', text:'梅ってさ、寒い時期に一番先に咲くんだよ。桜より先に。' },
{ type:'text', speaker:'さくら', text:'うん。' },
{ type:'text', speaker:'ホーリーくん', text:'FC水戸も、そんな感じだったと思う。まだ何もない時期に、先に咲いた。' },
{ type:'text', speaker:'さくら', text:'……詩的だね、ホーリーくん。' },
{ type:'text', speaker:'ホーリーくん', text:'体重310kgでも詩は言えるよ。' },
{ type:'text', speaker:'さくら', text:'なんでそこで体重言うの！？' },

// 選択肢② 共感度影響大
{ type:'label', label:'choice2' },
{ type:'text', speaker:'ホーリーくん', text:'FC水戸が始まった頃のこと、もっと知りたい？' },
{ type:'choice', choices:[
  { text:'もっと聞かせて。4部からって、すごくない？', next:'choice2a', empathy:18 },
  { text:'今のホーリーホックと、関係あるの？', next:'choice2b', empathy:0 },
  { text:'Jリーグを目指すって、そんな簡単に言えること？', next:'choice2c', empathy:-12 },
]},
{ type:'label', label:'choice2a' },
{ type:'text', speaker:'ホーリーくん', text:'すごいよ。でも石山さんにとっては、自然なことだったと思う。ここにチームがなければ、子どもたちの夢もない。そう思ったら、やるしかない。' },
{ type:'jump', to:'scene14' },
{ type:'label', label:'choice2b' },
{ type:'text', speaker:'ホーリーくん', text:'関係ある。FC水戸があったから今がある。全部つながってるんだ。' },
{ type:'jump', to:'scene14' },
{ type:'label', label:'choice2c' },
{ type:'text', speaker:'ホーリーくん', text:'……簡単じゃないよ。でも言わなかったら、始まらない。' },

// Scene 1-4: 偕楽園を歩きながら
{ type:'label', label:'scene14' },
{ type:'label_display', text:'Scene 1-4　偕楽園を歩きながら' },
{ type:'text', speaker:'さくら', text:'で、FC水戸は3年で県2部まで上がったんだっけ。' },
{ type:'text', speaker:'ホーリーくん', text:'準優勝まで行った。でも1997年に大きな転機があって。' },
{ type:'text', speaker:'さくら', text:'転機？' },
{ type:'text', speaker:'ホーリーくん', text:'プリマハム土浦FC、ってチームが廃部になりそうになったんだ。実業団のチームで、JFLにいた。' },
{ type:'text', speaker:'さくら', text:'JFL？' },
{ type:'text', speaker:'ホーリーくん', text:'Jリーグの一個下のリーグ。そこに合併して入れてもらったんだよ、FC水戸が。' },
{ type:'text', speaker:'さくら', text:'合併……って、大変じゃなかったの？' },
{ type:'text', speaker:'ホーリーくん', text:'大変だったよ。でも、それで「水戸ホーリーホック」になった。オレの名前がついたクラブに。' },
{ type:'text', monologue:true, text:'……ホーリーくんの名前のクラブ、か。\nなんか、それは大事な話だな。' },
{ type:'text', speaker:'さくら', text:'そのとき、ホーリーくんは……いたの？' },
{ type:'text', speaker:'ホーリーくん', text:'オレは2002年生まれだよ、公式には。でもクラブの記憶は全部知ってる。' },
{ type:'text', speaker:'さくら', text:'なんで？' },
{ type:'text', speaker:'ホーリーくん', text:'そういうもんだから。' },
{ type:'text', speaker:'さくら', text:'……そういうもんか。' },

// =============== 第2章: 青い海と、14連敗の話 ===============
{ type:'label', label:'chapter2' },
{ type:'se', se:'scene_change' },
{ type:'scene', text:'第2章　青い海と、14連敗の話\n1997〜1999年　合併・JFL時代' },

// Scene 2-1: ひたち海浜公園 ネモフィラ
{ type:'bg', bg:'nemophila', bgOverlay:'clear' },
{ type:'bgm', bgm:'bright' },
{ type:'label_display', text:'Scene 2-1　ひたち海浜公園　ネモフィラ' },
{ type:'text', monologue:true, text:'4月の終わり。ホーリーくんが「ネモフィラが咲いてる」と言って、アツマーレの前でわたしを待っていた。' },
{ type:'text', monologue:true, text:'（みはらしの丘が一面、澄んだ青に染まっている。）', showHolly:true },
{ type:'text', speaker:'さくら', text:'……うわあ。' },
{ type:'text', speaker:'ホーリーくん', text:'うわあ、でしょ。' },
{ type:'text', speaker:'さくら', text:'何この青。すごい。見渡す限りに青がある。' },
{ type:'text', speaker:'ホーリーくん', text:'この青、ホーリーホックの色だよ。' },
{ type:'text', speaker:'さくら', text:'言いたかったんだね、その一言。' },
{ type:'text', speaker:'ホーリーくん', text:'ずっと言いたかった。' },
{ type:'text', monologue:true, text:'その一言のために連れてきたのか……まあ、でも確かにこの青はホーリーホックの青だな。' },
{ type:'text', monologue:true, text:'（二人で丘を歩きながら。青い花畑に囲まれている。）' },
{ type:'text', speaker:'さくら', text:'この前の続き、聞かせて。合併してからのこと。' },
{ type:'text', speaker:'ホーリーくん', text:'1997年ね。JFL初年度。' },
{ type:'text', speaker:'さくら', text:'どうだったの？' },
{ type:'text', speaker:'ホーリーくん', text:'開幕14連敗。' },
{ type:'text', speaker:'さくら', text:'……重いな、最初の言葉が。' },
{ type:'text', speaker:'ホーリーくん', text:'14試合連続で負けたんだよ。' },
{ type:'text', speaker:'さくら', text:'それ、解散とかしないの？' },
{ type:'text', speaker:'ホーリーくん', text:'しない。するわけないじゃん。' },
{ type:'text', monologue:true, text:'なんでそんなに自信満々に言えるの……' },

// Scene 2-2: 14連敗の話
{ type:'label_display', text:'Scene 2-2　14連敗の話' },
{ type:'text', speaker:'ホーリーくん', text:'14連敗してね、7月に川崎フロンターレに勝ったんだ。1-0。クラブ初勝利。' },
{ type:'text', speaker:'さくら', text:'7月まで勝てなかったの！？' },
{ type:'text', speaker:'ホーリーくん', text:'うん。でもそのときのスタジアムの雰囲気、すごかったって聞いてる。' },
{ type:'text', speaker:'さくら', text:'どんな感じだったんだろ。' },
{ type:'text', speaker:'ホーリーくん', text:'ひとつ勝つことが、こんなにうれしいんだって。みんなで泣いたんだって。' },
{ type:'text', speaker:'さくら', text:'……14連敗したあとの1勝って、普通の1勝じゃないね。' },
{ type:'text', speaker:'ホーリーくん', text:'そうだよ。大事なのは順番じゃなくて、重さだよ。' },
{ type:'text', speaker:'さくら', text:'重さ。' },
{ type:'text', speaker:'ホーリーくん', text:'どんな思いを積み上げたかで、1勝の重さが変わる。' },
{ type:'text', monologue:true, text:'それ、すごく……なんか、刺さる言葉だな。' },

// 選択肢③
{ type:'text', speaker:'ホーリーくん', text:'14連敗でも諦めなかった人たちのこと、どう思う？' },
{ type:'choice', choices:[
  { text:'すごいと思う。でもそれって、普通じゃできないよ', next:'choice3a', empathy:18 },
  { text:'14連敗って、普通にやばいじゃん……', next:'choice3b', empathy:0 },
  { text:'なんでやめなかったんだろ。もったいなくない？', next:'choice3c', empathy:-12 },
]},
{ type:'label', label:'choice3a' },
{ type:'text', speaker:'ホーリーくん', text:'普通じゃないから、今があるんだよ。普通の人は諦めるから。' },
{ type:'jump', to:'scene23' },
{ type:'label', label:'choice3b' },
{ type:'text', speaker:'ホーリーくん', text:'やばいよ。でも、やばいって気にしてる場合じゃなかったんだと思う。' },
{ type:'jump', to:'scene23' },
{ type:'label', label:'choice3c' },
{ type:'text', speaker:'ホーリーくん', text:'……もったいなくないよ。ここにあることが、全部の理由だから。' },

// Scene 2-3: ソフトクリームと1999年
{ type:'label', label:'scene23' },
{ type:'label_display', text:'Scene 2-3　ソフトクリームと1999年' },
{ type:'text', monologue:true, text:'（二人でソフトクリームを食べながら歩く。）' },
{ type:'text', speaker:'さくら', text:'で、その後J2に上がったんだよね？' },
{ type:'text', speaker:'ホーリーくん', text:'1999年。JFLのセカンドステージで首位になって、年間3位でJ2昇格決めた。' },
{ type:'text', speaker:'さくら', text:'いきなり首位？' },
{ type:'text', speaker:'ホーリーくん', text:'セカンドステージだけね。前半は苦戦してたけど、後半持ち直した。' },
{ type:'text', speaker:'さくら', text:'そういうの、なんか好きだな。後半から強くなるやつ。' },
{ type:'text', speaker:'ホーリーくん', text:'さくらは後半型なんだね。' },
{ type:'text', speaker:'さくら', text:'え、わたし？' },
{ type:'text', speaker:'ホーリーくん', text:'うん。水戸に来てから、後半型になってきてる。' },
{ type:'text', speaker:'さくら', text:'……なんでわかるの、そんなこと。' },
{ type:'text', speaker:'ホーリーくん', text:'水戸のこと全部知ってるから、水戸に来た人のこともなんとなくわかる。' },
{ type:'text', speaker:'さくら', text:'それ、少し怖いんだけど。' },
{ type:'text', speaker:'ホーリーくん', text:'怖くないよ。ただそういうもんだから。' },
{ type:'text', monologue:true, text:'「そういうもん」で全部片付けるの、ずるいな。でも不思議と、怖くはない。' },

// =============== 第3章: 門番と呼ばれた空 ===============
{ type:'label', label:'chapter3' },
{ type:'se', se:'scene_change' },
{ type:'scene', text:'第3章　門番と呼ばれた空\n2000年代〜2010年代　J2長期在籍' },

// Scene 3-1: 千波湖畔 夕暮れ
{ type:'bg', bg:'senba', bgOverlay:'evening' },
{ type:'bgm', bgm:'melancholy' },
{ type:'label_display', text:'Scene 3-1　千波湖畔　夕暮れ' },
{ type:'se', se:'wind' },
{ type:'text', monologue:true, text:'夏の終わり。ホーリーくんと千波湖の湖畔を歩いていた。', showHolly:true },
{ type:'text', monologue:true, text:'夕焼けが水面に映って、湖が燃えているみたいだった。' },
{ type:'text', speaker:'さくら', text:'J2参入からずっとJ2にいたって言ってたけど、どのくらい？' },
{ type:'text', speaker:'ホーリーくん', text:'2000年から2025年、今シーズンまで。26シーズン。' },
{ type:'text', speaker:'さくら', text:'26……' },
{ type:'text', speaker:'ホーリーくん', text:'「J2の門番」って言われてたよ。' },
{ type:'text', speaker:'さくら', text:'門番……' },
{ type:'text', speaker:'ホーリーくん', text:'昇格も降格もせずに、ずっとJ2にいる。門の前に立ってるみたいだから、門番。' },
{ type:'text', monologue:true, text:'（少し沈黙。夕焼けが湖に映る。）' },
{ type:'text', speaker:'さくら', text:'それ、言った人はどういうつもりで言ったんだろ。' },
{ type:'text', speaker:'ホーリーくん', text:'どういう意味？' },
{ type:'text', speaker:'さくら', text:'馬鹿にして言ったのか、愛情を込めて言ったのか、って。' },
{ type:'text', speaker:'ホーリーくん', text:'両方だと思うよ。' },
{ type:'text', speaker:'さくら', text:'両方か。' },
{ type:'text', speaker:'ホーリーくん', text:'でも、オレは嫌いじゃなかった。「門番」って言葉。' },
{ type:'text', speaker:'さくら', text:'なんで？' },
{ type:'text', speaker:'ホーリーくん', text:'ずっとそこにいる、ってことだから。どんなことがあっても、いなくなってない。' },
{ type:'text', monologue:true, text:'……それ、すごく。\nホーリーくんみたいな言い方だな。' },

// Scene 3-2: 財政難の話
{ type:'label_display', text:'Scene 3-2　財政難の話' },
{ type:'text', speaker:'さくら', text:'でも、26年間ってお金も大変だったんじゃないの？' },
{ type:'text', speaker:'ホーリーくん', text:'大変だったよ。何度かギリギリだったこともある。' },
{ type:'text', speaker:'さくら', text:'ギリギリって……消えそうになったの？' },
{ type:'text', speaker:'ホーリーくん', text:'そういうこともあった。でも、そのたびに誰かが助けてくれた。' },
{ type:'text', speaker:'さくら', text:'誰が？' },
{ type:'text', speaker:'ホーリーくん', text:'サポーターが募金してくれたり、地元の企業が出資してくれたり、市が動いてくれたり。' },
{ type:'text', speaker:'さくら', text:'みんなで支えてたんだ。' },
{ type:'text', speaker:'ホーリーくん', text:'うん。親会社がないから、倒れそうになったら地域全体で踏ん張るしかない。' },
{ type:'text', speaker:'さくら', text:'それって、弱いってこと？　それとも強いってこと？' },
{ type:'text', speaker:'ホーリーくん', text:'……両方だと思う。でも、なくなってないから。それが答えかな。' },

// Scene 3-3: 光さん
{ type:'label_display', text:'Scene 3-3　長年のサポーター・光さん' },
{ type:'text', monologue:true, text:'（屋台で焼き鳥を買っていると、青いユニフォームを着たおじさんが声をかけてくる。）' },
{ type:'text', speaker:'光さん', text:'ホーリー！久しぶりじゃん。' },
{ type:'text', speaker:'ホーリーくん', text:'光さん、元気？' },
{ type:'text', speaker:'光さん', text:'元気だよ。……その子、新しい人？' },
{ type:'text', speaker:'ホーリーくん', text:'さくら。最近水戸に来た。' },
{ type:'text', speaker:'光さん', text:'へえ。（さくらに向かって）水戸ホーリーホック、試合見た？' },
{ type:'text', speaker:'さくら', text:'あ、はい。一回見ました。' },
{ type:'text', speaker:'光さん', text:'どうだった？' },
{ type:'text', speaker:'さくら', text:'楽しかったです。引き分けでしたけど。' },
{ type:'text', speaker:'光さん', text:'引き分けはもう慣れてるから大丈夫。……俺、もう15年来てるけど、慣れたことといえば引き分けと空振りの応援だよ。' },
{ type:'text', speaker:'さくら', monologue:true, text:'（小声でホーリーくんに）この人、大丈夫？' },
{ type:'text', speaker:'ホーリーくん', text:'（小声で）大丈夫。ただ正直なだけ。' },
{ type:'text', speaker:'光さん', text:'でも来るんだよね、俺。何があっても。それが不思議でさ。' },
{ type:'text', speaker:'さくら', text:'なんで来るんですか？' },
{ type:'text', speaker:'光さん', text:'なんでだろな……（しばらく考えて）……負けた日の方が、翌週来たくなるんだよ。' },
{ type:'text', speaker:'さくら', text:'え、なんで？' },
{ type:'text', speaker:'光さん', text:'腑に落ちないじゃん、負けると。だから確かめに来る。次は勝てるかもって。' },
{ type:'text', speaker:'さくら', text:'それ、沼じゃないですか。' },
{ type:'text', speaker:'光さん', text:'沼だよ。でもいい沼だよ。' },

// Scene 3-4: 2005年天皇杯
{ type:'bg', bg:'senba2', bgOverlay:'night' },
{ type:'bgm', bgm:'warm' },
{ type:'label_display', text:'Scene 3-4　2005年天皇杯' },
{ type:'text', speaker:'さくら', text:'J2長期在籍って、ずっと苦しいことばかりだったの？' },
{ type:'text', speaker:'ホーリーくん', text:'いいこともあったよ。2005年、天皇杯でガンバ大阪に勝ったんだ。' },
{ type:'text', speaker:'さくら', text:'ガンバ大阪って……J1の、強いチームだよね？' },
{ type:'text', speaker:'ホーリーくん', text:'そのとき優勝争いしてたチームに、J2の水戸が勝ったんだよ。3対2。延長戦で。' },
{ type:'text', speaker:'さくら', text:'え、それすごくない！？' },
{ type:'text', speaker:'ホーリーくん', text:'すごかったよ。初めてJ1のクラブから公式戦で勝った試合。' },
{ type:'text', speaker:'さくら', text:'そのときのスタジアム、どんな感じだったの？' },
{ type:'text', speaker:'ホーリーくん', text:'……もう、ずっと叫んでた。みんな。抱き合ってた。泣いてた。' },
{ type:'text', speaker:'さくら', text:'ホーリーくんも？' },
{ type:'text', speaker:'ホーリーくん', text:'（少し照れたように）……泣いてたかもしれない。' },
{ type:'text', speaker:'さくら', text:'ホーリーくんも泣くんだ。' },
{ type:'text', speaker:'ホーリーくん', text:'泣くよ。体重310kgでも泣く。' },
{ type:'text', speaker:'さくら', text:'また体重言った。' },
{ type:'text', monologue:true, text:'（二人で笑う。夜の湖畔に笑い声が響く。）' },

// 選択肢④
{ type:'text', speaker:'ホーリーくん', text:'26年間、この街で続けてきたことの意味、わかる気がする？' },
{ type:'choice', choices:[
  { text:'なんとなく、わかってきた。負けても来るって、そういうことかなって', next:'choice4a', empathy:18 },
  { text:'まだわからないけど……もう少し聞いてみたい', next:'choice4b', empathy:8 },
  { text:'J1に上がれなかったのに、続けた意味ってあるの？', next:'choice4c', empathy:-12 },
]},
{ type:'label', label:'choice4a' },
{ type:'text', speaker:'ホーリーくん', text:'そう。負けても来るって、信じてるってことだから。勝ち負けよりも大事なものがある、って知ってるってことだから。' },
{ type:'jump', to:'chapter4' },
{ type:'label', label:'choice4b' },
{ type:'text', speaker:'ホーリーくん', text:'うん。ゆっくり聞いていい。急がなくていい。' },
{ type:'jump', to:'chapter4' },
{ type:'label', label:'choice4c' },
{ type:'text', speaker:'ホーリーくん', text:'あるよ。……いつかわかると思う。' },

// =============== 第4章: 次の50年のために ===============
{ type:'label', label:'chapter4' },
{ type:'se', se:'scene_change' },
{ type:'scene', text:'第4章　次の50年のために\n2010年代〜2020年代　経営改革' },

// Scene 4-1: 大洗 磯前神社
{ type:'bg', bg:'torii', bgOverlay:'morning' },
{ type:'bgm', bgm:'warm' },
{ type:'label_display', text:'Scene 4-1　大洗　磯前神社' },
{ type:'text', monologue:true, text:'10月。ホーリーくんが「大洗に行こう」と言った。', showHolly:true },
{ type:'text', monologue:true, text:'神磯の鳥居は、岩礁の上に立っていた。海に向かって、ただそこにある。' },
{ type:'text', speaker:'さくら', text:'ここ、どういう場所なの？' },
{ type:'text', speaker:'ホーリーくん', text:'神様が降り立った岩礁だよ。ずっと前から、ここにある。' },
{ type:'text', speaker:'さくら', text:'ずっと前から……ホーリーくんに似てるね。ずっとそこにいる、って。' },
{ type:'text', speaker:'ホーリーくん', text:'そう思う？' },
{ type:'text', speaker:'さくら', text:'うん。' },
{ type:'se', se:'wind' },
{ type:'text', monologue:true, text:'（波が鳥居に打ち寄せる。朝の光が海に反射する。）' },
{ type:'text', speaker:'ホーリーくん', text:'クラブも、ここみたいな場所であればいいなって思うんだよ。' },
{ type:'text', speaker:'さくら', text:'どういう意味？' },
{ type:'text', speaker:'ホーリーくん', text:'波が来ても、揺れても、ここにある。壊れない。それだけで、意味がある。' },
{ type:'text', speaker:'さくら', text:'……それが経営改革の話につながるの？' },
{ type:'text', speaker:'ホーリーくん', text:'つながるよ。「50年後もここにあるクラブ」を作る話だから。' },

// Scene 4-2: 経営の話
{ type:'bg', bg:'oarai', bgOverlay:'afternoon' },
{ type:'bgm', bgm:'jazz' },
{ type:'label_display', text:'Scene 4-2　経営の話' },
{ type:'text', monologue:true, text:'（あんこう鍋を前にしながら話す二人。）' },
{ type:'text', speaker:'さくら', text:'あんこう鍋、初めて食べた。おいしい……' },
{ type:'text', speaker:'ホーリーくん', text:'茨城の冬はこれだよ。' },
{ type:'text', speaker:'さくら', text:'で、経営改革って何をしたの？' },
{ type:'text', speaker:'ホーリーくん', text:'クラブの社長が変わったりしながら、「勝利だけ追うんじゃなくて、地域と一緒に育つクラブ」を目指すようになった。' },
{ type:'text', speaker:'さくら', text:'地域と一緒に育つ？' },
{ type:'text', speaker:'ホーリーくん', text:'福祉とか、教育とか、まちづくりとか。サッカーだけじゃなくて、地域に必要なことをクラブがやる。' },
{ type:'text', speaker:'さくら', text:'それって……プロのサッカークラブがやることなの？' },
{ type:'text', speaker:'ホーリーくん', text:'親会社のないクラブだから、できることでもある。この街と一緒に生きてるから。' },
{ type:'text', speaker:'さくら', text:'収支とか、厳しいんじゃないの？' },
{ type:'text', speaker:'ホーリーくん', text:'厳しいよ。でも「数字だけ追っても魂は死ぬ」ってこともわかってる。' },
{ type:'text', speaker:'さくら', text:'誰がそう言ったの？' },
{ type:'text', speaker:'ホーリーくん', text:'いろんな人が、それぞれの言葉で言ってきた。' },
{ type:'text', monologue:true, text:'いろんな人が、それぞれの言葉で。\nそれってつまり、そういうことを考えてきた人が、ここに何人もいたってことだ。' },

// Scene 4-3: アツマーレへ
{ type:'bg', bg:'atsumare', bgOverlay:'afternoon' },
{ type:'bgm', bgm:'bright' },
{ type:'label_display', text:'Scene 4-3　アツマーレへ' },
{ type:'text', monologue:true, text:'大洗からの帰り道、ホーリーくんがアツマーレに連れて行ってくれた。\n城里町。山の中の、緑に囲まれた場所。' },
{ type:'text', speaker:'さくら', text:'ここが……クラブハウスだよね。前に来たとこ。' },
{ type:'text', speaker:'ホーリーくん', text:'うん。アツマーレ。城里町の七会町民センターがクラブハウスになってる。' },
{ type:'text', speaker:'さくら', text:'町民センターが？' },
{ type:'text', speaker:'ホーリーくん', text:'地域と一緒に、ってそういうこと。クラブだけの施設じゃなくて、みんなの場所に間借りしてる。' },
{ type:'text', speaker:'さくら', text:'なんか……すごく、水戸ホーリーホックっぽいな。' },
{ type:'text', speaker:'ホーリーくん', text:'そうでしょ。' },
{ type:'text', monologue:true, text:'（練習を終えた選手たちがグラウンドから戻ってくる。ホーリーくんが手を振る。選手が笑顔で手を振り返す。）' },
{ type:'text', monologue:true, text:'なんかいい光景だな。\nマスコットと選手が、普通に手を振り合ってる。\nそれがここのクラブなんだ。' },

// 選択肢⑤
{ type:'text', speaker:'ホーリーくん', text:'クラブって、何のためにあると思う？' },
{ type:'choice', choices:[
  { text:'街のためにあると思う。ここに来てそれがわかった気がする', next:'choice5a', empathy:18 },
  { text:'勝つためじゃないの？', next:'choice5b', empathy:0 },
  { text:'わからないけど、考えてみたい', next:'choice5c', empathy:8 },
]},
{ type:'label', label:'choice5a' },
{ type:'text', speaker:'ホーリーくん', text:'……そう言ってくれてよかった。それがわかると、全部がつながって見えるから。' },
{ type:'jump', to:'final_chapter' },
{ type:'label', label:'choice5b' },
{ type:'text', speaker:'ホーリーくん', text:'それもある。でもそれだけじゃない。勝てない時期が26年続いても、クラブがなくならなかった理由が、他にあるから。' },
{ type:'jump', to:'final_chapter' },
{ type:'label', label:'choice5c' },
{ type:'text', speaker:'ホーリーくん', text:'考えてくれてありがとう。焦らなくていい。' },

// =============== 最終章: 門の外へ ===============
{ type:'label', label:'final_chapter' },
{ type:'se', se:'scene_change' },
{ type:'scene', text:'最終章　門の外へ\n2025年　J2優勝・J1昇格' },

// Scene Final-1: シーズン最終盤
{ type:'bg', bg:'stadium_facade', bgOverlay:'night' },
{ type:'bgm', bgm:'tense' },
{ type:'label_display', text:'Scene Final-1　シーズン最終盤' },
{ type:'text', monologue:true, text:'11月。水戸ホーリーホックは、J2優勝・J1昇格まであと一歩のところにいた。', showHolly:true },
{ type:'text', monologue:true, text:'26年で初めての、その位置に。' },
{ type:'text', monologue:true, text:'（スタジアムの外周。夜。明日の試合に備えて、係員がフラッグを設置している。）' },
{ type:'text', speaker:'さくら', text:'明日、決まるかもしれないね。' },
{ type:'text', speaker:'ホーリーくん', text:'かもしれない。' },
{ type:'text', speaker:'さくら', text:'ホーリーくん、緊張してる？' },
{ type:'se', se:'heartbeat' },
{ type:'text', speaker:'ホーリーくん', text:'……してる。' },
{ type:'text', speaker:'さくら', text:'え、初めて聞いた。ホーリーくんが緊張するって。' },
{ type:'text', speaker:'ホーリーくん', text:'そりゃするよ。26年待ってたんだから。' },
{ type:'text', monologue:true, text:'（夜のスタジアムを二人で見上げる。バックスタンドの「MITO」の文字が暗闇に浮かんでいる。）' },
{ type:'text', speaker:'さくら', text:'一回聞いていい？' },
{ type:'text', speaker:'ホーリーくん', text:'なに？' },
{ type:'text', speaker:'さくら', text:'ホーリーくんは……J1に行きたかった？　昇格できなかった年、悔しかった？' },
{ type:'text', speaker:'ホーリーくん', text:'……悔しかったよ。毎年。' },
{ type:'text', speaker:'さくら', text:'でも笑ってたよね、ずっと。サポーターの前で。' },
{ type:'text', speaker:'ホーリーくん', text:'笑うしかないじゃん。オレが暗くなったら、みんな暗くなるから。' },
{ type:'text', monologue:true, text:'ずっとそこにいて、ずっと笑って、ずっと待って。\n26年。\nそれがどれだけのことか、今日初めてわかった気がする。' },
{ type:'text', speaker:'さくら', text:'ホーリーくん。明日、一緒に見てもいい？' },
{ type:'text', speaker:'ホーリーくん', text:'もちろん。一緒に見よう。ずっと隣にいるから。' },

// Scene Final-2: 昇格の瞬間
{ type:'label', label:'final_2' },
{ type:'bg', bg:'stadium', bgOverlay:'evening' },
{ type:'bgm', bgm:'climax' },
{ type:'se', se:'cheer' },
{ type:'label_display', text:'Scene Final-2　昇格の瞬間　2025年11月29日' },
{ type:'text', monologue:true, text:'スタジアムは満員だった。' },
{ type:'text', monologue:true, text:'1万人を超える人が来ていた。青いユニフォームが、スタンド全体を埋め尽くしていた。' },
{ type:'text', monologue:true, text:'光さんも、それぞれの場所で叫んでいた。' },
{ type:'text', monologue:true, text:'（試合が進む。後半30分。スコアは水戸2点リード。大分に2-0。）' },
{ type:'text', speaker:'さくら', text:'（息を殺しながら）あと、何分……' },
{ type:'text', speaker:'ホーリーくん', text:'（目を細めて前を向きながら）……もうすぐ。' },
{ type:'se', se:'whistle' },
{ type:'text', monologue:true, text:'（試合終了のホイッスル。）' },
{ type:'text', monologue:true, text:'（一瞬の沈黙。）' },
{ type:'se', se:'cheer' },
{ type:'text', monologue:true, text:'（そして——爆発するような歓声。）' },
{ type:'text', speaker:'光さん', text:'（遠くで）昇格——！！！！' },
{ type:'text', monologue:true, text:'（場内アナウンスが流れる。「長崎は引き分け——水戸ホーリーホック、J2優勝決定！」）' },
{ type:'se', se:'sparkle' },
{ type:'text', monologue:true, text:'（もう一度、スタジアムが爆発した。）' },
{ type:'text', monologue:true, text:'（さくらが気づくと、泣いていた。なんで泣いているのか、自分でもわからなかった。）' },
{ type:'text', monologue:true, text:'（でも、涙は止まらなかった。）' },
{ type:'text', speaker:'ホーリーくん', text:'……来た。' },
{ type:'text', speaker:'さくら', text:'（泣きながら）来たね。' },
{ type:'text', speaker:'ホーリーくん', text:'長かったな。でも、来た。' },
{ type:'text', speaker:'さくら', text:'26年。' },
{ type:'text', speaker:'ホーリーくん', text:'うん。26年。' },
{ type:'text', monologue:true, text:'（ホーリーくんが、そっとさくらの隣に立つ。）' },
{ type:'text', monologue:true, text:'（ピッチでは選手たちが抱き合い、スタンドからは紙テープが舞っていた。）' },
{ type:'text', monologue:true, text:'（青い空間が、白く輝いた。）' },
{ type:'text', monologue:true, text:'あとから、友達に言ったら笑われた。\n「なんで自分のクラブでもないのに泣くの」と。' },
{ type:'text', monologue:true, text:'でも、うまく説明できなかった。\nそこにある理由を知ったら、誰だって泣くと思う。\nそう思ったから。' },

// Scene Final-3: 分岐点
{ type:'label', label:'final_3' },
{ type:'bg', bg:'stadium_facade', bgOverlay:'night' },
{ type:'bgm', bgm:'ending' },
{ type:'label_display', text:'Scene Final-3' },
{ type:'text', monologue:true, text:'（選手のセレモニーが終わり、人が少しずつ帰っていく。さくらとホーリーくんだけ残っている。）' },
{ type:'text', speaker:'ホーリーくん', text:'来年も、ホームに来てくれる？' },

// 最終選択肢
{ type:'choice', choices:[
  { text:'来る。来年も、その次も、ずっと来る', next:'good_end', empathy:0, requireEmpathy:60, overrideEnd:'good' },
  { text:'……来たいけど、来られるかわからない', next:'bad_end', empathy:0, overrideEnd:'bad' },
]},

// =============== GOOD END: 葵、咲く ===============
{ type:'label', label:'good_end' },
{ type:'bgm', bgm:'ending' },
{ type:'text', speaker:'さくら', text:'来る。来年も、その次も、ずっと来る。' },
{ type:'text', monologue:true, text:'（ホーリーくんが少し驚いたような顔をした。）' },
{ type:'text', monologue:true, text:'（それから、ゆっくりと——本当にゆっくりと——笑った。）' },
{ type:'text', speaker:'ホーリーくん', text:'……うん。' },
{ type:'text', speaker:'ホーリーくん', text:'一緒にいてくれてありがとう。' },
{ type:'text', speaker:'さくら', text:'え、お礼言う感じなの？' },
{ type:'text', speaker:'ホーリーくん', text:'言うよ。ずっと一人でここにいたから。' },
{ type:'text', monologue:true, text:'……ずっと一人で。\n26年間。ここで待ち続けて、笑い続けて、ひとりで。' },
{ type:'text', speaker:'さくら', text:'ひとりじゃないよ、もう。' },
{ type:'text', speaker:'ホーリーくん', text:'うん。知ってる。' },
{ type:'se', se:'wind' },
{ type:'text', monologue:true, text:'（夜風が吹いた。スタジアムの外灯が、二人を照らした。）' },
{ type:'text', monologue:true, text:'（遠くで、サポーターたちがまだ歌っている声が聞こえた。）' },
{ type:'text', speaker:'ホーリーくん', text:'来年から——2026シーズンからJ1だよ。スタジアムも変わる。' },
{ type:'text', speaker:'さくら', text:'スタジアム変わるの？' },
{ type:'text', speaker:'ホーリーくん', text:'うん。笠松ってとこ。もっと大きい。J1の基準を満たしてるから。' },
{ type:'text', speaker:'さくら', text:'……ここじゃなくなるんだ。' },
{ type:'text', speaker:'ホーリーくん', text:'でも、水戸のクラブはここにあるから。場所が変わっても、ホームはホームだよ。' },
{ type:'text', speaker:'さくら', text:'……そっか。' },
{ type:'text', speaker:'ホーリーくん', text:'来てくれる？　笠松にも。' },
{ type:'text', speaker:'さくら', text:'行く。絶対行く。' },
{ type:'text', speaker:'ホーリーくん', text:'（ゆっくり、でも確かに）……うん。' },
{ type:'text', speaker:'ホーリーくん', text:'強い相手がいっぱいくる。でも大丈夫だよ。だってオレたちがいるから。' },
{ type:'text', speaker:'さくら', text:'「オレたち」って言った。' },
{ type:'text', speaker:'ホーリーくん', text:'言った。' },
{ type:'text', monologue:true, text:'その夜、水戸の街が青く輝いていた気がした。' },
{ type:'se', se:'sparkle' },
{ type:'text', monologue:true, text:'葵の花が、26年ぶりに——\nようやく、大きく咲いた。' },
{ type:'ending', title:'GOOD END', subtitle:'「葵、咲く」', endType:'good' },

// =============== BAD END: また来年 ===============
{ type:'label', label:'bad_end' },
{ type:'bgm', bgm:'sad' },
{ type:'text', speaker:'さくら', text:'……来たいけど、来られるかわからない。' },
{ type:'text', monologue:true, text:'（ホーリーくんは少し黙った。）' },
{ type:'text', monologue:true, text:'（それから、うなずいた。）' },
{ type:'text', speaker:'ホーリーくん', text:'うん。' },
{ type:'text', speaker:'さくら', text:'怒ってる？' },
{ type:'text', speaker:'ホーリーくん', text:'怒ってない。' },
{ type:'text', speaker:'さくら', text:'……ごめん、なんか。' },
{ type:'text', speaker:'ホーリーくん', text:'謝らなくていい。来られないときもある。それが普通だから。' },
{ type:'se', se:'wind' },
{ type:'text', monologue:true, text:'（ホーリーくんが、スタジアムを見上げた。）' },
{ type:'text', speaker:'ホーリーくん', text:'でも……オレはここにいるから。' },
{ type:'text', speaker:'さくら', text:'……うん。' },
{ type:'text', speaker:'ホーリーくん', text:'また来年も、いるから。' },
{ type:'text', monologue:true, text:'その言葉が、すごく寂しかった。\n寂しいと思ったのは、わたしが、来たいと思ってるからだ。' },
{ type:'text', monologue:true, text:'来たいのに、来られるかわからないと言った。\nなぜそうしてしまったのか、しばらく考えた。' },
{ type:'text', monologue:true, text:'── ✦ ──' },
{ type:'text', monologue:true, text:'次のホームゲームの日、わたしはスタジアムの近くを通った。' },
{ type:'text', monologue:true, text:'応援歌の声が聞こえた。\n足が止まった。' },
{ type:'text', monologue:true, text:'——やっぱり、来てしまった。' },
{ type:'text', monologue:true, text:'（スタジアムのゲートに、ホーリーくんがいた。）', showHolly:true },
{ type:'text', monologue:true, text:'（ホーリーくんはさくらを見て、ゆっくりと手を振った。）' },
{ type:'text', speaker:'ホーリーくん', text:'来た。' },
{ type:'text', speaker:'さくら', text:'来た。' },
{ type:'text', speaker:'ホーリーくん', text:'知ってた。' },
{ type:'text', speaker:'さくら', text:'なんで。' },
{ type:'text', speaker:'ホーリーくん', text:'そういうもんだから。' },
{ type:'text', monologue:true, text:'来年も、きっとここに来る。\nそれだけは、わかった。' },
{ type:'ending', title:'BAD END', subtitle:'「また来年」', endType:'bad' },

];

// Background image mapping
const BG_MAP = {
  'residential': 'images/bg_stadium_facade.jpg',
  'stadium': 'images/bg_stadium.jpg',
  'stadium_facade': 'images/bg_stadium_facade.jpg',
  'nemophila': 'images/bg_nemophila.jpg',
  'senba': 'images/bg_senba_lake.jpg',
  'senba2': 'images/bg_senba_lake2.jpg',
  'plum': 'images/bg_plum_kairakuen.jpg',
  'torii': 'images/bg_torii.jpg',
  'oarai': 'images/bg_oarai_shrine.jpg',
  'atsumare': 'images/bg_atsumare.jpg',
};

// Background overlay styles
const OVERLAY_MAP = {
  'morning': 'linear-gradient(to bottom, rgba(255,220,150,0.15), rgba(255,180,100,0.1))',
  'afternoon': 'linear-gradient(to bottom, rgba(200,220,255,0.1), rgba(150,180,220,0.05))',
  'evening': 'linear-gradient(to bottom, rgba(255,120,50,0.2), rgba(100,50,150,0.15))',
  'night': 'linear-gradient(to bottom, rgba(10,10,40,0.5), rgba(20,20,60,0.4))',
  'clear': 'none',
};
